"""create ApplicationForm model

Revision ID: 3b7b4e9aebe7
Revises: bb92f353c598
Create Date: 2025-04-17 18:47:53.250371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7b4e9aebe7'
down_revision = 'bb92f353c598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('nomor_hp', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('kecamatan', sa.String(length=50), nullable=False),
    sa.Column('kota', sa.String(length=50), nullable=False),
    sa.Column('provinsi', sa.String(length=50), nullable=False),
    sa.Column('tipe_produk', sa.String(length=50), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('jangka_waktu', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_form')
    # ### end Alembic commands ###
