"""Update ApplicationForm to allow non unique email value

Revision ID: 53907ec6302b
Revises: 3b7b4e9aebe7
Create Date: 2025-04-17 19:56:52.356427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53907ec6302b'
down_revision = '3b7b4e9aebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_form', schema=None) as batch_op:
        batch_op.drop_constraint('application_form_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_form', schema=None) as batch_op:
        batch_op.create_unique_constraint('application_form_email_key', ['email'])

    # ### end Alembic commands ###
