name: Deploy Production (Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/safepick-backend:prod .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/safepick-backend:prod

  deploy:
    name: Pull and Run on VPS (Production)
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop and Remove Old Container
        run: |
          docker stop safepick-backend-prod || true
          docker rm safepick-backend-prod || true

      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/safepick-backend:prod

      - name: Run New Container
        run: |
          docker run -d \
            --name safepick-backend-prod \
            --network safepick-prod-network \
            --env-file ~/safepick-prod/safepick-service/.env \
            -p 8008:5000 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/safepick-backend:prod
